### ISSUE TITLE
Research Apple Calendar API

### ISSUE THREAD

**Issue by Prasana-sys** [EECE3093C/team-project-moncef#16]
Figure out how to use Apple's Calendar API to work .NET C# and add link to documentation here.

**Comment by prkshsmn** [comment]
Any links?

**Comment by Prasana-sys** [comment]
Doesn't currently seem possible at this stage of development as the API can only be accessed with programming languages like Swift and Objective C. https://developer.apple.com/documentation/foundation/calendar. So I'm closing this for now.
