### ISSUE TITLE
Research on Canvas API

### ISSUE THREAD

**Issue by Prasana-sys** [EECE3093C/team-project-moncef#17]

**Comment by prkshsmn** [comment]
Any links?

**Comment by Prasana-sys** [comment]
https://canvas.instructure.com/doc/api/account_calendars.html
https://community.canvaslms.com/t5/Canvas-Developers-Group/NET-Canvas-API-Implementation/ba-p/269365

How does it work?
The associated source code will create a command line tool that accepts a config file.  The config file contains the following information:

"accessToken" - your access token
"apiUrl" - the url to your Canvas site, I would you Beta or Test
"apiCalls" - array of API calls that you would like to run, including parameters
For simplicity and purposes of demo, the access token and API url are in this config file.

The format of the API call list is an array of pipe delimited strings in the following format:

[method name] | [param1],[value1] | [param2],[value2] | .... | [param(n)],[value(n)]
These strings will be parsed and passed to the API library where they will be converted into actual calls to the Canvas API, at the site defined by the "apiUrl" variable.

This sample config includes GET, POST, and PUT calls, to demonstrate each type of verb.

Each verb is implemented in the base class: clsHttpMethods.cs

Full response details are logged by NLog.  Grab these responses and inspect them for full details.  If your test produces an error or throws an exception, full details can also be found in the log file.  If you use my default nlog.config, log files will be found in this location:  c:\\logs\canvasApiTest\*.log

**Comment by Prasana-sys** [comment]
It is possible to implement this in our current structure of the project.
