### ISSUE TITLE
Research on Google Calendar API

### ISSUE THREAD

**Issue by Prasana-sys** [EECE3093C/team-project-moncef#18]

**Comment by prkshsmn** [comment]
Create a new project in the Google Developers Console:

    Go to https://console.developers.google.com/ and sign in with your Google account
    Click on "Create Project" and give your project a name
    Click on "Create" to create the project

Enable the Google Calendar API for your project:

    In the sidebar, click on "APIs & Services" and then "Dashboard"
    Click on "Enable APIs and Services"
    Search for "Google Calendar API" and click on it
    Click on "Enable"

Create API credentials:

    In the sidebar, click on "APIs & Services" and then "Credentials"
    Click on "Create Credentials" and select "OAuth client ID"
    Select "Desktop App" as the application type
    Give your OAuth client ID a name
    Click on "Create"
    Click on "Download" to download the credentials to your local machine

Add the Google Calendar API NuGet package to your project:

    In Visual Studio, right-click on your project and select "Manage NuGet Packages"
    Search for "Google.Apis.Calendar" and install the package

**Comment by Prasana-sys** [comment]
Looks good!
