### ISSUE TITLE
Initialize Project Directory Structure

### ISSUE THREAD

**Issue by HamzaKhairy** [EECE3093C/team-project-moncef#24]
https://github.com/EECE3093C/supplementary_materials/blob/main/resources_by_topic.md

**Comment by Prasana-sys** [comment]
Hey @HamzaKhairy, how's this going?

**Comment by HamzaKhairy** [comment]
The project directory structure looks good. I think our root looks great, please confirm then you can ping me to close the issue.

**Comment by Prasana-sys** [comment]
@HamzaKhairy yeah looks good
