### ISSUE TITLE
Document Google Calender API setup

### ISSUE THREAD

**Issue by prkshsmn** [EECE3093C/team-project-moncef#36]
Link to website: https://developers.google.com/calendar/api/guides/overview

For .NET: https://developers.google.com/api-client-library/dotnet/apis/calendar/v3

Create a new project in the Google Developers Console:

    Go to https://console.developers.google.com/ and sign in with your Google account
    Click on "Create Project" and give your project a name
    Click on "Create" to create the project

Enable the Google Calendar API for your project:

    In the sidebar, click on "APIs & Services" and then "Dashboard"
    Click on "Enable APIs and Services"
    Search for "Google Calendar API" and click on it
    Click on "Enable"

Create API credentials:

    In the sidebar, click on "APIs & Services" and then "Credentials"
    Click on "Create Credentials" and select "OAuth client ID"
    Select "Desktop App" as the application type
    Give your OAuth client ID a name
    Click on "Create"
    Click on "Download" to download the credentials to your local machine

Add the Google Calendar API NuGet package to your project:

    In Visual Studio, right-click on your project and select "Manage NuGet Packages"
    Search for "Google.Apis.Calendar" and install the package

**Comment by Prasana-sys** [comment]
I think it would be easier for you to use your own account for debugging purposes.

**Comment by prkshsmn** [comment]
aye aye captain

**Comment by prkshsmn** [comment]
As of Iteration 4:

                        UserCredential credential;

                        // Load client secrets file
                        using (var stream = new FileStream("credentials.json", FileMode.Open, FileAccess.Read))
                        {
                            string credPath = "token.json";
                            credential = GoogleWebAuthorizationBroker.AuthorizeAsync(
                                GoogleClientSecrets.FromStream(stream).Secrets,
                                new[] { CalendarService.Scope.Calendar },
                                "user",
                                CancellationToken.None,
                                new FileDataStore(credPath, true)).Result;
                        }

with respective credentials.json file
