### ISSUE TITLE
Gcal Delete Event

### ISSUE THREAD

**Issue by prkshsmn** [EECE3093C/team-project-moncef#52]

**Comment by prkshsmn** [comment]
case 2:
    Console.WriteLine("Google Selected");
    UserCredential credential;

    // Load client secrets file
    using (var stream = new FileStream("credentials.json", FileMode.Open, FileAccess.Read))
    {
        string credPath = "token.json";
        credential = GoogleWebAuthorizationBroker.AuthorizeAsync(
            GoogleClientSecrets.FromStream(stream).Secrets,
            new[] { CalendarService.Scope.Calendar },
            "user",
            CancellationToken.None,
            new FileDataStore(credPath, true)).Result;
    }

    // Create Google Calendar API service
    var service = new CalendarService(new BaseClientService.Initializer()
    {
        HttpClientInitializer = credential,
        ApplicationName = "MonCal",
    });

    Console.WriteLine("Enter event name to delete: ");
    string eventNameToDelete = Console.ReadLine();

    // Get list of events from the primary calendar
    EventsResource.ListRequest listRequest = service.Events.List("primary");
    listRequest.TimeMin = DateTime.UtcNow;
    listRequest.ShowDeleted = false;
    listRequest.SingleEvents = true;
    listRequest.MaxResults = 1000;
    listRequest.OrderBy = EventsResource.ListRequest.OrderByEnum.StartTime;
    Events events = listRequest.Execute();

    // Search for the event to delete
    foreach (var eventItem in events.Items)
    {
        if (eventItem.Summary == eventNameToDelete)
        {
            Console.WriteLine("Deleting event: {0} ({1})", eventItem.Summary, eventItem.Id);
            service.Events.Delete("primary", eventItem.Id).Execute();
            Console.WriteLine("Event deleted.");
            break;
        }
    }
    break;

**Comment by prkshsmn** [comment]
Updated code 4/21/2023:

`                                    //Start remove event

                                    Console.WriteLine("Enter event name to delete: ");
                                    string eventNameToDelete = Console.ReadLine();

                                    // Get list of events from the primary calendar
                                    EventsResource.ListRequest listRequest = service.Events.List("primary");
                                    listRequest.TimeMin = DateTime.UtcNow;
                                    listRequest.ShowDeleted = false;
                                    listRequest.SingleEvents = true;
                                    listRequest.MaxResults = 1000;
                                    listRequest.OrderBy = EventsResource.ListRequest.OrderByEnum.StartTime;
                                    Events events = listRequest.Execute();

                                    // Search for the event to delete
                                    foreach (var eventItem in events.Items)
                                    {
                                        if (eventItem.Summary == eventNameToDelete)
                                        {
                                            Console.WriteLine("Deleting event: {0} ({1})", eventItem.Summary, eventItem.Id);
                                            service.Events.Delete("primary", eventItem.Id).Execute();
                                            Console.WriteLine("Event deleted.");
                                            break;
                                        }
                                    
                                    break;`

**Comment by Prasana-sys** [comment]
Looks good to me!
