### ISSUE TITLE
Gcal Edit Event

### ISSUE THREAD

**Issue by prkshsmn** [EECE3093C/team-project-moncef#53]

**Comment by prkshsmn** [comment]
The MonCal CLI program allows users to create and manage events in Google Calendar. In addition to adding and removing events, users can now edit events using the program. The new "Edit Event" feature is accessible through the Google Calendar menu and allows users to modify event details such as the event name, start and end times, and event description. The program uses the Google Calendar API to perform these operations, ensuring that events are accurately updated in the user's calendar. This feature provides users with a convenient way to manage their schedules, whether it's updating the details of an existing event or making last-minute changes to their plans. The documentation for this feature in the MonCal CLI program provides clear instructions on how to use the program to edit events in Google Calendar.

**Comment by prkshsmn** [comment]
https://developers.google.com/calendar/api/v3/reference/events/update

**Comment by Prasana-sys** [comment]
I think is enough to get started working on this
