### ISSUE TITLE
Add devcontainer files to repo

### ISSUE THREAD

**Issue by Prasana-sys** [EECE3093C/team-project-moncef#64]
the devcontainer files should be part of the repo so that it remains consistent across all developers' computers. This should not be ignored in the .gitignore file.

**Comment by Prasana-sys** [comment]
@HamzaKhairy @prkshsmn does this look good?

**Comment by HamzaKhairy** [comment]
Looks great, I double checked gitignore as well.

**Comment by Prasana-sys** [comment]
Cool 😎

**Comment by prkshsmn** [comment]
10/10 great work!
