### ISSUE TITLE
GCal Delete Event Code

### ISSUE THREAD

**Issue by prkshsmn** [EECE3093C/team-project-moncef#65]
This function deletes an event from the user's Google Calendar.It prompts the user for the event ID, retrieves the event from the calendar, and then deletes it using the Google Calendar API. If the event is successfully deleted, a confirmation message is printed to the console. If an error occurs, an exception is thrown.

**Comment by prkshsmn** [comment]
`                                case 2:
                                    /
                                    //Start remove event

                                    Console.WriteLine("Enter event name to delete: ");
                                    string eventNameToDelete = Console.ReadLine();

                                    // Get list of events from the primary calendar
                                    EventsResource.ListRequest listRequest = service.Events.List("primary");
                                    listRequest.TimeMin = DateTime.UtcNow;
                                    listRequest.ShowDeleted = false;
                                    listRequest.SingleEvents = true;
                                    listRequest.MaxResults = 1000;
                                    listRequest.OrderBy = EventsResource.ListRequest.OrderByEnum.StartTime;
                                    Events events = listRequest.Execute();

                                    // Search for the event to delete
                                    foreach (var eventItem in events.Items)
                                    {
                                        if (eventItem.Summary == eventNameToDelete)
                                        {
                                            Console.WriteLine("Deleting event: {0} ({1})", eventItem.Summary, eventItem.Id);
                                            service.Events.Delete("primary", eventItem.Id).Execute();
                                            Console.WriteLine("Event deleted.");
                                            break;
                                        }
                                    
                                    break;`

**Comment by Prasana-sys** [comment]
Nice
