### ISSUE TITLE
GCal Edit Event Code

### ISSUE THREAD

**Issue by prkshsmn** [EECE3093C/team-project-moncef#66]
This function allows the user to edit an existing event in their Google Calendar. It prompts the user for the event ID and retrieves the event from the calendar using the Google Calendar API. The function then prompts the user to enter the updated event information, including the event name, start time, and end time. The updated information is used to modify the event, which is then updated in the calendar using the Google Calendar API. If the event is successfully updated, a confirmation message is printed to the console. If an error occurs, an exception is thrown.

**Comment by prkshsmn** [comment]
`                                 case 3:
                                    //Start edit event
                                    Console.WriteLine("Edit event in Google Calendar selected");

                                    // Load client secrets file
                                    using (var stream = new FileStream("credentials.json", FileMode.Open, FileAccess.Read))
                                    {
                                        string credPath = "token.json";
                                        credential = GoogleWebAuthorizationBroker.AuthorizeAsync(
                                            GoogleClientSecrets.FromStream(stream).Secrets,
                                            new[] { CalendarService.Scope.Calendar },
                                            "user",
                                            CancellationToken.None,
                                            new FileDataStore(credPath, true)).Result;
                                    }

                                    // Create Google Calendar API service
                                    service = new CalendarService(new BaseClientService.Initializer()
                                    {
                                        HttpClientInitializer = credential,
                                        ApplicationName = "MonCal",
                                    });

                                    Console.WriteLine("Enter the ID of the event to edit: ");
                                    string eventId = Console.ReadLine();

                                    // Get the event to edit
                                    var eventToEdit = service.Events
                                    break;`

**Comment by Prasana-sys** [comment]
LGTM!
