### ISSUE TITLE
Move unnecessary img or png files from the root

### ISSUE THREAD

**Issue by Prasana-sys** [EECE3093C/team-project-moncef#67]

**Comment by Prasana-sys** [comment]
@prkshsmn @HamzaKhairy Do you guys think the current repo struture looks good or do we need to do something else?

**Comment by HamzaKhairy** [comment]
Good, my bad about the imgs. I assumed you moved them during our iteration 4 wrap up meeting.

**Comment by Prasana-sys** [comment]
> Good, my bad about the imgs. I assumed you moved them during our iteration 4 wrap up meeting.

I guess there was some miscommunication. But glad we caught that.

**Comment by prkshsmn** [comment]
Looks good to me.
