### ISSUE TITLE
Research GitHub Actions

### ISSUE THREAD

**Issue by prkshsmn** [EECE3093C/team-project-moncef#71]
Find how to use GitHub Actions

**Comment by prkshsmn** [comment]
https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

**Comment by prkshsmn** [comment]
https://www.youtube.com/watch?v=efQWMv9KS9A

**Comment by prkshsmn** [comment]
https://learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-best-practices

**Comment by Prasana-sys** [comment]
https://learn.microsoft.com/en-us/dotnet/core/tutorials/testing-library-with-visual-studio-code?pivots=dotnet-7-0

This site shows the steps to create unit tests for C# in vs code.
