### ISSUE TITLE
Problem with Unit Tests and Git Actions

### ISSUE THREAD

**Issue by prkshsmn** [EECE3093C/team-project-moncef#72]
Not getting my Unit test file to run to run the add event unit test

File is: gcal > unittesting.json

**Comment by Prasana-sys** [comment]
@prkshsmn 
Unit test are not a json, they will be a .cs file in our case.

Aside from that, I deleted the previous .yml file as that was for .net wpf applications, which we were not developing for. Instead, I've created this new "dotnet.yml" file that should solve this problem.
